# Dependencies
markdown:         redcarpet
highlighter:      pygments

exclude:          ['.asset_pipeline', 'deploy.sh', 'server-script.sh']

# Permalinks
#permalink:        pretty
permalink:        /:title

# Setup
title:            Saurabh Meena's Public Diary
description:      "a pragmatic approach to world"
url:              https://err0w.github.io/
#url:              http://localhost:4000
baseurl:          /

author:
  name:           Saurabh Meena
  url:            https://twitter.com/mr_fountainhead
  email:          sourabhmeena381@gmail.com


# Custom vars
github:           https://github.com/err0w
twitter:          https://twitter.com/mr_fountainhead
instagram:    https://www.instagram.com/mr_fountainhead
linkedin:     https://www.linkedin.com/in/smeena007/

version:          1.0

asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  display_path: assets       # Default = nil
  gzip: true              # Default = false
